import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import { abi } from "../constants/abi";
import { contractAddress } from "../constants/contract-address";
import { useState, useEffect } from "react";
import { ethers } from "ethers";

const inter = Inter({ subsets: ["latin"] });

export const injected = new InjectedConnector(); // MetaMask connection (window.ethereum)

export default function Home() {
  const [hasMetamask, setHasMetamask] = useState(false);

  useEffect(() => {
    if (typeof window.ethereum !== "undefined") {
      setHasMetamask(true);
    }
  });

  const {
    active,
    activate,
    chainId,
    account,
    library: provider, // web3 provider instance from the connected MetaMask wallet
  } = useWeb3React();

  async function connect() {
    if (typeof window.ethereum !== "undefined") {
      try {
        await activate(injected); // used to connect MetaMask
        setHasMetamask(true);
      } catch (e) {
        console.log(e);
      }
    } else {
      console.log("Please install MetaMask");
    }
  }

  async function execute() {
    if (active) {
      const signer = provider.getSigner();
      const contract = new ethers.Contract(contractAddress, abi, signer);
      try {
        await contract.store(42);
      } catch (error) {
        console.log(error);
      }
    } else {
      console.log("Please install MetaMask");
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          {hasMetamask ? (
            active ? (
              "Connected! "
            ) : (
              <button onClick={() => connect()}>Connect</button>
            )
          ) : (
            "Please install metamask"
          )}

          {active ? <button onClick={() => execute()}>Execute</button> : ""}
        </div>
      </main>
    </>
  );
}
